package socs.network.message;

import java.io.Serializable;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Link State Advertisement generated by each router.
 * its state can be modified by multiple channel threads.
 * thread safe ensured by using java concurrent constructs.
 */
public class LSA implements Serializable {

  //IP address of the router originate this LSA
  public final String linkStateID;
  public AtomicInteger lsaSeqNumber = new AtomicInteger(Integer.MIN_VALUE);
  public ConcurrentLinkedDeque<LinkDescription> links = new ConcurrentLinkedDeque<LinkDescription>();

  public LSA(String linkStateID) {
    this.linkStateID = linkStateID;
  }

  @Override
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(linkStateID + ":").append(lsaSeqNumber + "\n");
    for (LinkDescription ld : links) {
      sb.append(ld);
    }
    sb.append("\n");
    return sb.toString();
  }
}
